"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-shared_token_remove"
description = "Allows the shared_token_remove command without prearguments."
commands.allow = ["shared_token_remove"]
