"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-shared_token_get"
description = "Allows the shared_token_get command without prearguments."
commands.allow = ["shared_token_get"]
