"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "deny-init_activation"
description = "Denies the init_activation command without prearguments."
commands.deny = ["init_activation"]
