"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "deny-shared_token_remove"
description = "Denies the shared_token_remove command without prearguments."
commands.deny = ["shared_token_remove"]
