"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "deny-poll_activation"
description = "Denies the poll_activation command without prearguments."
commands.deny = ["poll_activation"]
