"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "deny-open_activation_url"
description = "Denies the open_activation_url command without prearguments."
commands.deny = ["open_activation_url"]
