"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "deny-get_platform_info"
description = "Denies the get_platform_info command without prearguments."
commands.deny = ["get_platform_info"]
